# These are supported funding model platforms

github: # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [vcsc.com.vn, invest.vcsc.com.vn, onlinetrading.vcsc.com.vn, bond.vcsc.com.vn]
patreon: # Replace with a single Patreon username
open_collective: # Replace with a single Open Collective username
ko_fi: # Replace with a single Ko-fi username: quang7hong81-vcsc
tidelift: # Replace with a single Tidelift platform-name/package-name e.g., quang7hong81-viet_capital_securities_joint_stock_company
community_bridge: # Replace with a single Community Bridge project-name e.g., quang7hong81-viet_capital_securities_joint_stock_company
liberapay: # Replace with a single Libera pay username: quang7hong81-viet_capital_securities_joint_stock_company
issuehunt: # Replace with a single IssueHunt username: quang7hong81-viet_capital_securities_joint_stock_company
otechie: # Replace with a single Otechie username: quang7hong81-viet_capital_securities_joint_stock_company
custom: # Replace with up to 4 custom sponsorship URLs e.g., ['vcsc.com.vn', 'invest.vcsc.com.vn', 'www.cafechungkhoan.com', www.vcsc.com.vn']
# Assignees: THONG NGO
