# These are supported funding model platfor 

github: # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [viet_capital_securities_jsc-vcsc, vcsc]
patreon: # Replace with a single Patreon username vcsc 
open_collective: # Replace with a single Open Collective username vcsc
ko_fi: # Replace with a single Ko-fi username: vcsc 
tidelift: # Replace with a single Tidelift platform-name/package-name e.g., viet capital securities
community_bridge: # Replace with a single Community Bridge project-name e.g., viet capital securities 
liberapay: # Replace with a single Libera pay username: vcsc
issuehunt: # Replace with a single IssueHunt username: vcsc 
otechie: # Replace with a single Otechie username: vcsc
custom: # Replace with up to 4 custom sponsorship URLs e.g., ['www.vcsc.com.vn', 'onlinetrading.vcsc.com.vn/v2/view/login/login.jsp?lang=vi','mobile.vcsc.com.vn', 'invest.vcsc.com.vn/mo-tai-khoan-online'] 

# assignees: THONG NGO 
  e-mail: quangthong1011@gmail.com
